### ISSUE TITLE
iPFTConfig.h Modul-Voreinstellung entspricht nicht der ReadMe

### ISSUE THREAD

**Issue by malchat** [UniSiegenCSCW/Shake#3]
In der iPFTConfig.h ist das Modul Redmine aktiviert welches laut ReadMe erst vom Entwickler aktiviert werden muss. Ebenso ist das Modul für die native Mail-App deaktiviert welches ja ebenso der ReadMe widerspricht.
Dazu kommt das im Quelltext erkennbar ist das nur eines der beiden Module beim aktuellen Stand benutzbar ist und nicht beide parallel, dies könnte in der ReadMe noch kenntlich gemacht werden.

**Comment by brodo** [comment]
Danke schon mal fürs reporten!
